### ISSUE TITLE
Definition of Exposure

### ISSUE THREAD

**Issue by Dave-stat** [MHaringa/insurancerating#1]
Thanks for awesome package. Sorry for asking so basic question - "What's the definition of Exposure in your example?". Is it the expected insured claim amount per claim?

**Comment by MHaringa** [comment]
Thanks for your question. In the example the term Exposure is a measure of what is being insured. For example, an insured vehicle is an exposure. If the vehicle is insured as of July 1 for a certain year, then during that year, this would represent an exposure of 0.5 to the insurance company. I will add a short description to the example.

**Comment by Dave-stat** [comment]
Thank you for reply. In the example 2 exposure is in 1000s for 100 claims. What does it signify in the example?

**Comment by MHaringa** [comment]
I am not sure whether i understand your question completely. An exposure of 1000 with 100 claims can be seen as 1000 vehicles with 100 claims. So the claim frequency is equal to 10 percent. 

If you have more insurance related questions please use for example https://stats.stackexchange.com. Use this issue section for questions related to the package.
