### ISSUE TITLE
Rename/redirect format_table

### ISSUE THREAD

**Issue by strengejacke** [MHaringa/insurancerating#3]
Hi Martin,
we're revising our API, and thereby want to rename some functions, in particular `insight::format_table()` should become `insight::export_table()` in the long run, while we feel that `insight::parameters_table()` should be actually named `format_table()`.

Thus, can you please change this code line:
https://github.com/MHaringa/insurancerating/blob/38968d2138747d7260182d436547774be8062965/R/model_performance.R#L61
and replace `insight::format_table()` with `insight::export_table()`? The updated _insight_ is on CRAN and has both names as aliases, so submitting an update for your package should work without problems.

This is no urgent request, but maybe you can try to update your package by mid of January 2021, so we can plan a smooth transition in renaming our functions from February 2021 on...

Daniel

**Comment by MHaringa** [comment]
Hi Daniel, 
thanks for the heads up. I replaced the code line. By mid of January 2021 I will submit an updated version to CRAN. 
Best, Martin

**Comment by strengejacke** [comment]
Hi Martin,
due to updates in other packages (namely, Matrix and MCMCglmm, I think), tests for the _parameter_ package on CRAN are failing. Thus an update was requested for that package, which in turn requires updating _insight_ first. I'll submit an update for insight the next days, which will break code / tests in your package on CRAN (as discussed here), but I'll inform CRAN that you're aware of this and have prepared an update to fix this issue. I hope this time schedule is OK for you.

**Comment by MHaringa** [comment]
Hi Daniel, thanks for the update. I submitted insurancerating to CRAN this morning.

**Comment by strengejacke** [comment]
Great, thanks!
