### ISSUE TITLE
add_prediction error for Tweedie glm

### ISSUE THREAD

**Issue by mlam-buckle** [MHaringa/insurancerating#4]
Hi MHaringa, thank you for building this package, it is very useful for our insurance application. I have just one question - it appears that the add_prediction function works for glms fitted with poisson or gamma, but when I tried to fit a tweedie model, the add_prediction gives an error about names not the same length as the vector. Is there any way to fix it or am I not supposed to use a Tweedie distribution for this?

Thanks a lot!

**Comment by MHaringa** [comment]
Hi Michelle, thank you for your question. It should be possible to use a Tweedie distribution in `add_prediction()`. `add_prediction()` is not restricted to work with Poisson or gamma. Can you give a reproducible example where an error is returned? 

Best, Martin

**Comment by MHaringa** [comment]
Hi Michelle, does this answer your question? 

``` r
library(tweedie)
library(statmod)
library(insurancerating)

y <- rgamma(20,shape=5)
x <- 1:20

twdeReg <- glm(y ~ x, family = tweedie(var.power = 1, link.power = 1))
data.frame(y, x) %>%
  add_prediction(., twdeReg)
#>           y  x pred_y_twdeReg
#> 1  7.777009  1       4.869800
#> 2  2.589581  2       4.871469
#> 3  5.274537  3       4.873138
#> 4  5.058212  4       4.874807
#> 5  8.987676  5       4.876476
#> 6  1.639357  6       4.878145
#> 7  5.315987  7       4.879814
#> 8  2.921094  8       4.881483
#> 9  4.528513  9       4.883152
#> 10 2.063999 10       4.884821
#> 11 5.680675 11       4.886490
#> 12 7.579458 12       4.888159
#> 13 3.956388 13       4.889828
#> 14 2.205680 14       4.891497
#> 15 5.610589 15       4.893166
#> 16 5.337189 16       4.894835
#> 17 3.159548 17       4.896504
#> 18 5.072243 18       4.898173
#> 19 7.977896 19       4.899842
#> 20 4.977473 20       4.901511
```

<sup>Created on 2022-05-26 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by mlam-buckle** [comment]
Thanks for your reply. I probably did not understand the correct usage of the function for add_prediction. Below is how I used it:

> mod1 <- glm(paid_amt/earned_days ~ gender + marital, family = tweedie(var.power=1.6,link.power=-0), data=bi, weights = earned_days)
> add_prediction(bi, mod1)
Error in names(df) <- var_nm : 
  'names' attribute [3] must be the same length as the vector [1]
>

**Comment by mlam-buckle** [comment]
Thanks for your reply. I probably did not understand the correct usage of the function for add_prediction. Below is how I used it:

> mod1 <- glm(paid_amt/earned_days ~ gender + marital, family = tweedie(var.power=1.6,link.power=-0), data=bi, weights = earned_days)
> add_prediction(bi, mod1)
Error in names(df) <- var_nm : 
  'names' attribute [3] must be the same length as the vector [1]
>

**Comment by MHaringa** [comment]
That seems the correct usage of `add_prediction()`. With the example above: 

``` r
library(tweedie)
library(statmod)
library(insurancerating)

y <- rgamma(20,shape=5)
x <- 1:20

bi <- data.frame(y, x)
mod1 <- glm(y ~ x, family = tweedie(var.power = 1, link.power = 1), data = bi)
add_prediction(bi, mod1)
#>           y  x pred_y_mod1
#> 1  5.679243  1    4.551451
#> 2  2.753178  2    4.533658
#> 3  4.232672  3    4.515865
#> 4  5.423829  4    4.498073
#> 5  5.416853  5    4.480280
#> 6  3.377315  6    4.462487
#> 7  7.072035  7    4.444695
#> 8  4.057077  8    4.426902
#> 9  2.141916  9    4.409109
#> 10 4.497836 10    4.391317
#> 11 2.239183 11    4.373524
#> 12 2.910234 12    4.355731
#> 13 7.135193 13    4.337939
#> 14 4.163510 14    4.320146
#> 15 8.602436 15    4.302353
#> 16 3.391173 16    4.284561
#> 17 2.273622 17    4.266768
#> 18 2.475307 18    4.248975
#> 19 4.054912 19    4.231183
#> 20 5.750884 20    4.213390

# Or you can rename the prediction column
add_prediction(bi, mod1, var = "prediction")
#>           y  x prediction
#> 1  5.679243  1   4.551451
#> 2  2.753178  2   4.533658
#> 3  4.232672  3   4.515865
#> 4  5.423829  4   4.498073
#> 5  5.416853  5   4.480280
#> 6  3.377315  6   4.462487
#> 7  7.072035  7   4.444695
#> 8  4.057077  8   4.426902
#> 9  2.141916  9   4.409109
#> 10 4.497836 10   4.391317
#> 11 2.239183 11   4.373524
#> 12 2.910234 12   4.355731
#> 13 7.135193 13   4.337939
#> 14 4.163510 14   4.320146
#> 15 8.602436 15   4.302353
#> 16 3.391173 16   4.284561
#> 17 2.273622 17   4.266768
#> 18 2.475307 18   4.248975
#> 19 4.054912 19   4.231183
#> 20 5.750884 20   4.213390
```

<sup>Created on 2022-05-26 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by mlam-buckle** [comment]
Yes I was able to solve it by renaming the prediction column. Thanks a lot for your help!
