### ISSUE TITLE
Bug in rating_factors1 with smoothed or restricted GLM

### ISSUE THREAD

**Issue by ArendJansen** [MHaringa/insurancerating#5]
[bug_report_rating_factors.txt](https://github.com/MHaringa/insurancerating/files/13488489/bug_report_rating_factors.txt)

The rating_factors1 function returns all smoothed and restricted coefficients equal to 1 when used on a 'refitsmooth' or 'refitrestricted' class of GLM.

I've added a code example as attachment,

this is a bug in the insurancerating::rating_factors1() function in version 0.7.2.

In line 160 of model_rating_factors.R:
'uit$values <- ifelse(is.na(uit$pvalues), 0, uit$values)'

I think should be:
'uit$pvalues <- ifelse(is.na(uit$pvalues), 0, uit$pvalues)'

**Comment by MHaringa** [comment]
Thank you for finding this. I can indeed reproduce your example, and it's true that this is not correct. I will address this in the new version of the package.

**Comment by MHaringa** [comment]
The issue has been resolved in the CRAN release (version 0.7.3). In this update, the redundancy between `rating_factors1()` and `rating_factors()` has been addressed. As a result, `rating_factors1()` has been deprecated, and users are now required to use `rating_factors()`.
